# -*- coding: utf-8 -*-
"""Web Scraping in R.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ypj7d3LHlF-0uC2PsEhcyscGS_3g97j

Web Scraping in R
"""

#necessary libraries to be imported:
library(httr) #sends http requests
library(jsonlite) #parses json responses
library(dplyr) #data manipulation

# Load necessary library
library(httr)
library(jsonlite)

# Define a function to get weather data for multiple cities
get_weather_data <- function(city_names) {
    all_data <- data.frame()  # Empty data frame to collect results

    for (city in city_names) {
        url <- 'https://api.openweathermap.org/data/2.5/forecast'  # Correct forecast endpoint

        # Define query parameters
        query <- list(
            q = city,
            appid = 'your_api_key_here',  # Correct param: 'appid' not 'appis'
            units = "metric"              # Correct: should be "metric", not "metrics"
        )

        # Send a GET request
        response <- GET(url, query = query)

        # Parse the response as a list
        data <- content(response, as = "parsed")

        # Only continue if forecast data exists
        if (!is.null(data$list)) {

            # Create a list of data frames for each forecast entry
            city_forecast <- lapply(data$list, function(entry) {
                data.frame(
                    city = city,
                    datetime = entry$dt_txt, #dt_txt: date and time in text format
                    temp = entry$main$temp,
                    humidity = entry$main$humidity,
                    weather = entry$weather[[1]]$main,
                    stringsAsFactors = FALSE
                )
            })

            # Combine the list of small data frames into one data frame
            city_forecast_df <- do.call(rbind, city_forecast)
            #rbind: combines dataframes row-wise
            #do.call(): calls the function rbind() and gives it all the elements of the list city_forecasts



            # Add to the master data frame
            all_data <- rbind(all_data, city_forecast_df)
        }
    }

    return(all_data)
}

# City list to get forecasts
cities <- c("Seoul", "London", "Paris")

# Call the function
weather_data <- get_weather_data(cities)

# Save the data to CSV
write.csv(weather_data, "cities_weather_forecast.csv", row.names = FALSE)

